# Generated by Django 5.0 on 2023-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_log_zns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.TextField()),
                ('template_code', models.CharField(max_length=11)),
                ('content', models.TextField()),
                ('type', models.SmallIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
    ]
