# Generated by Django 5.0 on 2023-12-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_log_zns', '0002_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlogzns',
            options={'managed': False},
        ),
    ]
