# Generated by Django 5.0 on 2023-12-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('balance_limit', models.BigIntegerField()),
                ('balance_current', models.BigIntegerField()),
                ('ip_limit', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.TextField()),
                ('template_code', models.CharField(max_length=11)),
                ('content', models.TextField()),
                ('type', models.SmallIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLogZNS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('content', models.TextField()),
                ('template_code', models.CharField(max_length=11)),
                ('template_type', models.SmallIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('response_msg_id', models.CharField(max_length=100)),
                ('response_error', models.CharField(max_length=10)),
                ('response_message', models.CharField(max_length=50)),
                ('zalo_sent_time', models.DateTimeField()),
                ('remaining_quota', models.CharField(max_length=50)),
                ('daily_quota', models.CharField(max_length=50)),
                ('sending_mode', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_log',
                'managed': False,
            },
        ),
    ]
