# Generated by Django 5.0 on 2023-12-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leeon_zns', '0002_transactionlogzn_delete_transactionlogzns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'verbose_name_plural': 'Danh sách khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'managed': False, 'verbose_name_plural': 'Các mẫu gửi tin'},
        ),
        migrations.AlterModelOptions(
            name='transactionlogzn',
            options={'managed': False, 'verbose_name_plural': 'Log giao dịch'},
        ),
    ]
